name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Running test cases
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.17]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    # - name: Build the application (if needed)
    #   run: npm run build --if-present

    # Install dependencies
    - name: Install depenedecies
      run: npm ci

    - name: List test files
      run: ls -la ./src/__tests__/auth

    - name: run npm
      run: |
        npm install
        npm i mocha
        npm install mocha-junit-reporter --save-dev

        
    # Run tests
    - name: Run tests
      run: |
        npm run start:test
    
#    # display test results
#     - name: Display test results 
#       run: |
#         echo "Test summary:"
#         grep 'passing' || echo "No tests passed."
#         grep 'failing' || echo "No tests failed."
    
    # Parse and display test results
    - name: Display test results summary
      run: |
        echo "Parsing test results..."
        echo "Total tests passed: $(grep -o 'testsuite.*tests="[0-9]*"' test-results.xml | sed -E 's/.*tests="([0-9]+)".*/\1/')"
        echo "Total tests failed: $(grep -o 'testsuite.*failures="[0-9]*"' test-results.xml | sed -E 's/.*failures="([0-9]+)".*/\1/')"

      # Optionally upload the test results file 
    - name: Upload test results file
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: test-results.xml
