name: Dependent Pipeline (Console Log)

on:
  repository_dispatch:
    types: [trigger-dependent-pipeline]

jobs:
  log:
    name: Generate Console Log
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v4

    - name: Check if Pipeline A was successful
      run: |
        if [[ "${{ github.event.client_payload.pipelineA_status }}" != "success" ]]; then
          echo "Pipeline A failed, aborting dependent pipeline."
          exit 1
        fi
        echo "Pipeline A completed successfully!"

    - name: Download test results  
      uses: actions/download-artifact@v3
      with:
        name: mochawesome-xml-report  
        path: test-results/**/*.xml

    - name: Check Integration Test Flag
      run: |
        if [[ "${{ github.event.client_payload.integration }}" == "true" ]]; then
          echo "Running integration tests because 'integration' flag is set."
        else
          echo "Skipping integration tests."
        fi

    - name: Check Unit Test Flag
      run: |
        if [[ "${{ github.event.client_payload.unit }}" == "true" ]]; then
          echo "Running unit tests because 'unit' flag is set."
        else
          echo "Skipping unit tests."
        fi

    - name: Print Success Log
      run: |
        echo "Now running dependent actions..."
        echo "This is a console.log from the dependent pipeline."
